In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [13]:
customer = pd.read_csv("Mall_Customers.csv")
#read the file

In [14]:
print("shape: ", customer.shape) #Checked how many rows and columns the dataset has
customer

shape:  (200, 5)

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [15]:
#Checking for missing values
customer.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [16]:
if customer.duplicated().sum() > 0:
    print(f"There are", customer.duplicated().sum())
else:
    print("There are no duplicate rows")

There are no duplicate rows

In [22]:
num_cols = customer.select_dtypes(include=['number']).columns
display(customer[num_cols][customer[num_cols] < 0])

     CustomerID  Age  Annual Income (k$)  Spending Score (1-100)
0           NaN  NaN                 NaN                     NaN
1           NaN  NaN                 NaN                     NaN
2           NaN  NaN                 NaN                     NaN
3           NaN  NaN                 NaN                     NaN
4           NaN  NaN                 NaN                     NaN
..          ...  ...                 ...                     ...
195         NaN  NaN                 NaN                     NaN
196         NaN  NaN                 NaN                     NaN
197         NaN  NaN                 NaN                     NaN
198         NaN  NaN                 NaN                     NaN
199         NaN  NaN                 NaN                     NaN

[200 rows x 4 columns]